{% set name = "towerpy" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/uobwatergroup/towerpy/archive/v{{ version }}.tar.gz
  sha256: c9704bf421700aba6567efcafaf6764f3636be4b3fc1bd6594bd0e0a330c57c6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  binary_relocation: False
  detect_binary_files_with_prefix: False

requirements:
  host:
    - python >=3
    - pip
    - setuptools_scm
  run:
    - python >=3.9
    - numpy
    - matplotlib-base >=3.8.0
    - scipy
    - cartopy
    - netCDF4

test:
  imports:
    - towerpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/uobwatergroup/towerpy
  summary: 'Towerpy, an open-source toolbox for processing polarimetric radar data'
  license: GPL-3.0-or-later
  license_file: LICENSE
  
  description: |
    Towerpy is a Python toolbox designed to read, process and display polarimetric radar data.
    Towerpy provides robust algorithms for radar data quality control and radar QPE.
    However, its use is not necessarily limited to meteorological or hydrological applications.
  dev_url: https://doi.org/10.1016/j.envsoft.2023.105746
  doc_url: https://towerpy.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - uobwatergroup
    - enchilaDaSzen
